let bookArray = [{
    "id": 1,
    "title": "Pushing Hands (Tui shou)",
    "author": "Adeline Rudiger",
    "genre": "Drama",
    "rating": 4.58,
    "year": 1999,
    "publisher": "Conroy LLC",
    "ISBN": "706237735-X",
    "binding": "casebound",
    "pages": 325,
    "language": "Azeri",
    "price": 41.33
  }, {
    "id": 2,
    "title": "$5 a Day",
    "author": "Veriee Purdon",
    "genre": "Comedy|Drama",
    "rating": 3.36,
    "year": 2000,
    "publisher": "Dickinson and Sons",
    "ISBN": "474929025-4",
    "binding": "paperback",
    "pages": 540,
    "language": "Chinese",
    "price": 43.97
  }, {
    "id": 3,
    "title": "Passion Flower",
    "author": "Arther Poulgreen",
    "genre": "Drama",
    "rating": 3.01,
    "year": 2011,
    "publisher": "Schuppe-Pacocha",
    "ISBN": "388574626-3",
    "binding": "spiral-bound",
    "pages": 576,
    "language": "Korean",
    "price": 49.15
  }, {
    "id": 4,
    "title": "Follow the Fleet",
    "author": "Reggie Slany",
    "genre": "Comedy|Musical|Romance",
    "rating": 3.27,
    "year": 2003,
    "publisher": "Schoen-West",
    "ISBN": "171149723-1",
    "binding": "leather-bound",
    "pages": 560,
    "language": "German",
    "price": 55.62
  }, {
    "id": 5,
    "title": "La discrète",
    "author": "Tomas Baudins",
    "genre": "Drama|Romance",
    "rating": 2.83,
    "year": 2000,
    "publisher": "Mosciski and Sons",
    "ISBN": "139459352-X",
    "binding": "hardcover",
    "pages": 113,
    "language": "Italian",
    "price": 43.52
  }, {
    "id": 6,
    "title": "11'09\"01 - September 11",
    "author": "Eleni Sustins",
    "genre": "Drama",
    "rating": 2.45,
    "year": 1990,
    "publisher": "Hammes Group",
    "ISBN": "670606947-7",
    "binding": "hardcover",
    "pages": 440,
    "language": "Montenegrin",
    "price": 8.13
  }, {
    "id": 7,
    "title": "Decameron, The (Decameron, Il)",
    "author": "Ardath Cockhill",
    "genre": "Comedy|Drama",
    "rating": 4.47,
    "year": 2003,
    "publisher": "Flatley Group",
    "ISBN": "368223351-2",
    "binding": "leather-bound",
    "pages": 619,
    "language": "Yiddish",
    "price": 61.19
  }, {
    "id": 8,
    "title": "Angele",
    "author": "Ansel Braganza",
    "genre": "Drama",
    "rating": 1.06,
    "year": 1997,
    "publisher": "Russel LLC",
    "ISBN": "032807896-4",
    "binding": "paperback",
    "pages": 293,
    "language": "Dutch",
    "price": 83.96
  }, {
    "id": 9,
    "title": "V/H/S",
    "author": "Rodrique Naulls",
    "genre": "Horror|Thriller",
    "rating": 2.53,
    "year": 2003,
    "publisher": "Denesik Inc",
    "ISBN": "168716949-7",
    "binding": "hardcover",
    "pages": 316,
    "language": "Polish",
    "price": 24.71
  }, {
    "id": 10,
    "title": "Misconception",
    "author": "Angelina Welbourn",
    "genre": "Documentary",
    "rating": 4.44,
    "year": 2000,
    "publisher": "Dooley, Wiegand and Ryan",
    "ISBN": "285323003-1",
    "binding": "spiral-bound",
    "pages": 415,
    "language": "Chinese",
    "price": 50.41
  }, {
    "id": 11,
    "title": "My Dear Desperado",
    "author": "Michael Tournay",
    "genre": "Comedy",
    "rating": 4.94,
    "year": 1987,
    "publisher": "Spencer, Murphy and Runte",
    "ISBN": "084288968-X",
    "binding": "casebound",
    "pages": 438,
    "language": "Bengali",
    "price": 11.94
  }, {
    "id": 12,
    "title": "Secret Adventures of Tom Thumb, The",
    "author": "Matelda Fink",
    "genre": "Adventure|Animation",
    "rating": 2.87,
    "year": 2006,
    "publisher": "Waelchi and Sons",
    "ISBN": "929980491-5",
    "binding": "leather-bound",
    "pages": 449,
    "language": "Thai",
    "price": 12.31
  }, {
    "id": 13,
    "title": "Ocean's Twelve",
    "author": "Jocko Zealander",
    "genre": "Action|Comedy|Crime|Thriller",
    "rating": 3.71,
    "year": 1988,
    "publisher": "Beer, Kautzer and Shields",
    "ISBN": "918077933-6",
    "binding": "leather-bound",
    "pages": 176,
    "language": "Malayalam",
    "price": 11.42
  }, {
    "id": 14,
    "title": "Damned, The (La Caduta degli dei)",
    "author": "Debee Hinrichs",
    "genre": "Drama|War",
    "rating": 2.59,
    "year": 2009,
    "publisher": "Lemke, Homenick and Stehr",
    "ISBN": "647453055-3",
    "binding": "paperback",
    "pages": 430,
    "language": "Tetum",
    "price": 18.94
  }, {
    "id": 15,
    "title": "Rubber",
    "author": "Adriane MacAskill",
    "genre": "Action|Adventure|Comedy|Crime|Drama|Film-Noir|Horror|Mystery|Thriller|Western",
    "rating": 3.76,
    "year": 1996,
    "publisher": "Kunde-O'Keefe",
    "ISBN": "561224176-3",
    "binding": "paperback",
    "pages": 627,
    "language": "Luxembourgish",
    "price": 64.6
  }, {
    "id": 16,
    "title": "Film Geek",
    "author": "Salvador Dandie",
    "genre": "Comedy",
    "rating": 3.81,
    "year": 1992,
    "publisher": "Johnston, Gulgowski and Stamm",
    "ISBN": "185740027-5",
    "binding": "hardcover",
    "pages": 12,
    "language": "Bislama",
    "price": 24.99
  }, {
    "id": 17,
    "title": "Suddenly, Last Winter (Improvvisamente l'inverno scorso)",
    "author": "Karla Benadette",
    "genre": "Documentary",
    "rating": 2.38,
    "year": 1997,
    "publisher": "Padberg and Sons",
    "ISBN": "346745566-2",
    "binding": "hardcover",
    "pages": 409,
    "language": "French",
    "price": 97.16
  }, {
    "id": 18,
    "title": "Mrs. Brown (a.k.a. Her Majesty, Mrs. Brown)",
    "author": "Rosabelle Davidman",
    "genre": "Drama|Romance",
    "rating": 1.28,
    "year": 2011,
    "publisher": "Hermiston-Gorczany",
    "ISBN": "271222038-2",
    "binding": "leather-bound",
    "pages": 710,
    "language": "Afrikaans",
    "price": 46.58
  }, {
    "id": 19,
    "title": "Loser",
    "author": "Camila McKelvie",
    "genre": "Comedy",
    "rating": 4.1,
    "year": 1990,
    "publisher": "Witting-Cronin",
    "ISBN": "229130085-7",
    "binding": "hardcover",
    "pages": 509,
    "language": "Khmer",
    "price": 93.93
  }, {
    "id": 20,
    "title": "Dinner Guest, The (L'invité)",
    "author": "Eveline Yoell",
    "genre": "Comedy",
    "rating": 4.35,
    "year": 1975,
    "publisher": "Muller-Fritsch",
    "ISBN": "213628231-X",
    "binding": "paperback",
    "pages": 994,
    "language": "Indonesian",
    "price": 44.97
  }, {
    "id": 21,
    "title": "Zero Theorem, The",
    "author": "Noland Simons",
    "genre": "Drama|Fantasy|Sci-Fi",
    "rating": 2.82,
    "year": 1999,
    "publisher": "Lesch and Sons",
    "ISBN": "948653370-9",
    "binding": "spiral-bound",
    "pages": 38,
    "language": "Gagauz",
    "price": 41.04
  }, {
    "id": 22,
    "title": "Which Way Is the Front Line From Here?  The Life and Time of Tim Hetherington",
    "author": "Lem Haggar",
    "genre": "Documentary",
    "rating": 1.78,
    "year": 2006,
    "publisher": "Jast-Olson",
    "ISBN": "579036159-5",
    "binding": "spiral-bound",
    "pages": 711,
    "language": "Dzongkha",
    "price": 79.84
  }, {
    "id": 23,
    "title": "Sittin' on a Backyard Fence",
    "author": "Eberto Minillo",
    "genre": "(no genres listed)",
    "rating": 3.58,
    "year": 1987,
    "publisher": "Bogan-Raynor",
    "ISBN": "476720802-5",
    "binding": "leather-bound",
    "pages": 276,
    "language": "Croatian",
    "price": 10.61
  }, {
    "id": 24,
    "title": "Asterix in Britain (Astérix chez les Bretons)",
    "author": "Yorgo Beswetherick",
    "genre": "Adventure|Animation|Children|Comedy",
    "rating": 4.02,
    "year": 1973,
    "publisher": "Bradtke-Halvorson",
    "ISBN": "686382039-0",
    "binding": "paperback",
    "pages": 904,
    "language": "Mongolian",
    "price": 29.78
  }, {
    "id": 25,
    "title": "Kelly & Cal",
    "author": "Dael Haskell",
    "genre": "Comedy|Drama",
    "rating": 3.46,
    "year": 1996,
    "publisher": "Greenfelder LLC",
    "ISBN": "720804786-3",
    "binding": "spiral-bound",
    "pages": 140,
    "language": "Georgian",
    "price": 48.11
  }, {
    "id": 26,
    "title": "One on One",
    "author": "Casey Sutliff",
    "genre": "Drama",
    "rating": 2.03,
    "year": 2004,
    "publisher": "Herman, Rempel and Maggio",
    "ISBN": "462072992-2",
    "binding": "spiral-bound",
    "pages": 406,
    "language": "Bosnian",
    "price": 57.15
  }, {
    "id": 27,
    "title": "Werewolf of London",
    "author": "Mari Crees",
    "genre": "Drama|Fantasy|Horror|Sci-Fi",
    "rating": 1.28,
    "year": 2011,
    "publisher": "O'Conner, Kunde and Ratke",
    "ISBN": "276881088-6",
    "binding": "casebound",
    "pages": 247,
    "language": "Haitian Creole",
    "price": 68.37
  }, {
    "id": 28,
    "title": "Cord (Hide and Seek)",
    "author": "Ulla Sargood",
    "genre": "Crime|Drama|Thriller",
    "rating": 1.59,
    "year": 2000,
    "publisher": "Stroman LLC",
    "ISBN": "586029569-3",
    "binding": "leather-bound",
    "pages": 1043,
    "language": "Gujarati",
    "price": 94.03
  }, {
    "id": 29,
    "title": "Sholay",
    "author": "Farr Hinkins",
    "genre": "Action|Adventure|Comedy|Musical|Romance|Thriller",
    "rating": 3.63,
    "year": 2010,
    "publisher": "Jacobi, Romaguera and Senger",
    "ISBN": "141342993-9",
    "binding": "casebound",
    "pages": 941,
    "language": "Bengali",
    "price": 42.55
  }, {
    "id": 30,
    "title": "Jack Frost",
    "author": "Buiron Sepey",
    "genre": "Children|Comedy|Drama",
    "rating": 3.86,
    "year": 1996,
    "publisher": "Witting-Boyer",
    "ISBN": "697601203-6",
    "binding": "paperback",
    "pages": 713,
    "language": "Maltese",
    "price": 40.24
  }, {
    "id": 31,
    "title": "X-Men",
    "author": "Margit Pinniger",
    "genre": "Action|Adventure|Sci-Fi",
    "rating": 2.42,
    "year": 1996,
    "publisher": "Borer, Hoeger and Bauch",
    "ISBN": "210089625-3",
    "binding": "paperback",
    "pages": 427,
    "language": "Chinese",
    "price": 74.74
  }, {
    "id": 32,
    "title": "Family Secrets (Familjehemligheter)",
    "author": "Desi Delmonti",
    "genre": "Drama",
    "rating": 2.38,
    "year": 1996,
    "publisher": "McCullough, Ziemann and Windler",
    "ISBN": "117591400-2",
    "binding": "spiral-bound",
    "pages": 648,
    "language": "French",
    "price": 54.33
  }, {
    "id": 33,
    "title": "Turtles Can Fly (Lakposhtha hâm parvaz mikonand)",
    "author": "Lorrie Farndon",
    "genre": "Drama|War",
    "rating": 1.98,
    "year": 1984,
    "publisher": "Kozey Inc",
    "ISBN": "005740300-7",
    "binding": "leather-bound",
    "pages": 412,
    "language": "Thai",
    "price": 48.67
  }, {
    "id": 34,
    "title": "Guy Thing, A",
    "author": "Adriane Stag",
    "genre": "Comedy|Romance",
    "rating": 2.49,
    "year": 1994,
    "publisher": "Pfeffer LLC",
    "ISBN": "123260478-X",
    "binding": "casebound",
    "pages": 631,
    "language": "Norwegian",
    "price": 76.8
  }, {
    "id": 35,
    "title": "The Land",
    "author": "Alice Sherwen",
    "genre": "Documentary",
    "rating": 4.22,
    "year": 2011,
    "publisher": "Cormier and Sons",
    "ISBN": "180771705-4",
    "binding": "spiral-bound",
    "pages": 69,
    "language": "Azeri",
    "price": 38.18
  }, {
    "id": 36,
    "title": "New Kind of Love, A",
    "author": "Worth Serman",
    "genre": "Comedy",
    "rating": 1.59,
    "year": 2004,
    "publisher": "Hoppe LLC",
    "ISBN": "617817212-5",
    "binding": "casebound",
    "pages": 57,
    "language": "Burmese",
    "price": 24.81
  }, {
    "id": 37,
    "title": "Chicago",
    "author": "Valencia Haining",
    "genre": "Comedy|Crime|Drama",
    "rating": 3.46,
    "year": 2011,
    "publisher": "Schowalter-Ernser",
    "ISBN": "467951457-4",
    "binding": "casebound",
    "pages": 384,
    "language": "Maltese",
    "price": 11.64
  }, {
    "id": 38,
    "title": "Hannah Montana: The Movie",
    "author": "Dehlia Lemmens",
    "genre": "Comedy|Drama|Musical|Romance",
    "rating": 4.66,
    "year": 1992,
    "publisher": "Olson Inc",
    "ISBN": "571526868-0",
    "binding": "hardcover",
    "pages": 192,
    "language": "Bosnian",
    "price": 52.02
  }, {
    "id": 39,
    "title": "Lynch",
    "author": "Brander Arnhold",
    "genre": "Documentary",
    "rating": 3.66,
    "year": 2012,
    "publisher": "Crooks-Senger",
    "ISBN": "880318668-9",
    "binding": "hardcover",
    "pages": 1044,
    "language": "Tamil",
    "price": 36.4
  }, {
    "id": 40,
    "title": "Horrorvision",
    "author": "Ellsworth Coulthard",
    "genre": "Horror",
    "rating": 3.84,
    "year": 1998,
    "publisher": "Terry-Bechtelar",
    "ISBN": "609156946-5",
    "binding": "leather-bound",
    "pages": 525,
    "language": "Georgian",
    "price": 83.09
  }, {
    "id": 41,
    "title": "Molly Maxwell",
    "author": "Tessi Halworth",
    "genre": "Drama|Romance",
    "rating": 3.35,
    "year": 1996,
    "publisher": "Hettinger Inc",
    "ISBN": "557014528-1",
    "binding": "hardcover",
    "pages": 157,
    "language": "Papiamento",
    "price": 85.75
  }, {
    "id": 42,
    "title": "Nun's Story, The",
    "author": "Keslie Pechard",
    "genre": "Drama",
    "rating": 3.41,
    "year": 2012,
    "publisher": "Rath and Sons",
    "ISBN": "465479006-3",
    "binding": "hardcover",
    "pages": 369,
    "language": "Romanian",
    "price": 5.32
  }, {
    "id": 43,
    "title": "Love of Siam, The (Rak haeng Siam)",
    "author": "Tarah Kopisch",
    "genre": "Drama|Mystery|Romance",
    "rating": 2.34,
    "year": 2006,
    "publisher": "Ritchie and Sons",
    "ISBN": "578855820-4",
    "binding": "spiral-bound",
    "pages": 825,
    "language": "Gujarati",
    "price": 11.74
  }, {
    "id": 44,
    "title": "Jay And Silent Bob's Super Groovy Cartoon Movie",
    "author": "Britt Farebrother",
    "genre": "(no genres listed)",
    "rating": 4.85,
    "year": 2008,
    "publisher": "Dietrich Inc",
    "ISBN": "483565683-0",
    "binding": "casebound",
    "pages": 576,
    "language": "Hebrew",
    "price": 79.88
  }, {
    "id": 45,
    "title": "Savage Three",
    "author": "Patsy Reeday",
    "genre": "Drama",
    "rating": 4.15,
    "year": 2009,
    "publisher": "Johnson Inc",
    "ISBN": "353870090-7",
    "binding": "leather-bound",
    "pages": 951,
    "language": "Kazakh",
    "price": 29.5
  }, {
    "id": 46,
    "title": "28 Weeks Later",
    "author": "Zack Petrushka",
    "genre": "Horror|Sci-Fi|Thriller",
    "rating": 2.97,
    "year": 1996,
    "publisher": "Wilderman-Treutel",
    "ISBN": "422888626-4",
    "binding": "spiral-bound",
    "pages": 28,
    "language": "Hindi",
    "price": 85.24
  }, {
    "id": 47,
    "title": "Vampire Hunter D: Bloodlust (Banpaia hantâ D)",
    "author": "Walt Crunden",
    "genre": "Animation|Fantasy|Horror|Sci-Fi",
    "rating": 1.22,
    "year": 2005,
    "publisher": "Funk-Christiansen",
    "ISBN": "416018840-0",
    "binding": "leather-bound",
    "pages": 53,
    "language": "Swedish",
    "price": 22.37
  }, {
    "id": 48,
    "title": "Androcles and the Lion",
    "author": "Sybyl Jachimak",
    "genre": "Comedy",
    "rating": 4.83,
    "year": 2010,
    "publisher": "Considine, Hauck and Kiehn",
    "ISBN": "734932008-6",
    "binding": "casebound",
    "pages": 528,
    "language": "English",
    "price": 11.54
  }, {
    "id": 49,
    "title": "The Second Best Exotic Marigold Hotel",
    "author": "Averill Ranyell",
    "genre": "Comedy|Drama",
    "rating": 3.69,
    "year": 2003,
    "publisher": "Wiza-Kuphal",
    "ISBN": "170208533-3",
    "binding": "leather-bound",
    "pages": 773,
    "language": "Haitian Creole",
    "price": 28.71
  }, {
    "id": 50,
    "title": "Jazz Singer, The",
    "author": "Sampson Adkins",
    "genre": "Musical",
    "rating": 1.35,
    "year": 2010,
    "publisher": "Harris, Stiedemann and Ritchie",
    "ISBN": "386900265-4",
    "binding": "hardcover",
    "pages": 1091,
    "language": "Afrikaans",
    "price": 45.81
  }, {
    "id": 51,
    "title": "Beauty Shop",
    "author": "Felice Sivell",
    "genre": "Comedy",
    "rating": 3.69,
    "year": 1993,
    "publisher": "Bergstrom-Nienow",
    "ISBN": "552331567-2",
    "binding": "leather-bound",
    "pages": 881,
    "language": "Latvian",
    "price": 12.04
  }, {
    "id": 52,
    "title": "Generation X",
    "author": "Gustavo Beadle",
    "genre": "Action|Adventure|Sci-Fi",
    "rating": 1.81,
    "year": 2009,
    "publisher": "Mertz Group",
    "ISBN": "462414839-8",
    "binding": "hardcover",
    "pages": 534,
    "language": "Catalan",
    "price": 24.55
  }, {
    "id": 53,
    "title": "Siberia",
    "author": "Lamont Potten",
    "genre": "Comedy",
    "rating": 4.83,
    "year": 1989,
    "publisher": "Runte LLC",
    "ISBN": "404729337-7",
    "binding": "hardcover",
    "pages": 663,
    "language": "Arabic",
    "price": 51.12
  }, {
    "id": 54,
    "title": "Damien: Omen II",
    "author": "Tracy Klaassens",
    "genre": "Horror",
    "rating": 1.1,
    "year": 1995,
    "publisher": "Ankunding LLC",
    "ISBN": "699537116-X",
    "binding": "leather-bound",
    "pages": 726,
    "language": "Malay",
    "price": 23.01
  }, {
    "id": 55,
    "title": "All of Me",
    "author": "Tyrone Larmuth",
    "genre": "Documentary",
    "rating": 3.79,
    "year": 1989,
    "publisher": "Beier, Hickle and Kuhn",
    "ISBN": "415980811-5",
    "binding": "paperback",
    "pages": 478,
    "language": "Hungarian",
    "price": 29.18
  }, {
    "id": 56,
    "title": "Denise Calls Up",
    "author": "Riki Bescoby",
    "genre": "Comedy",
    "rating": 2.98,
    "year": 1983,
    "publisher": "Littel, Waelchi and Huels",
    "ISBN": "498025054-8",
    "binding": "casebound",
    "pages": 555,
    "language": "Dzongkha",
    "price": 39.45
  }, {
    "id": 57,
    "title": "Spud",
    "author": "Angelita Heller",
    "genre": "Comedy",
    "rating": 4.42,
    "year": 1998,
    "publisher": "Cummerata-Wintheiser",
    "ISBN": "341577293-4",
    "binding": "paperback",
    "pages": 878,
    "language": "Thai",
    "price": 61.26
  }, {
    "id": 58,
    "title": "The Anomaly",
    "author": "Juditha Mackett",
    "genre": "Action|Sci-Fi|Thriller",
    "rating": 1.59,
    "year": 2011,
    "publisher": "Kris-Emard",
    "ISBN": "686883013-0",
    "binding": "spiral-bound",
    "pages": 825,
    "language": "Kashmiri",
    "price": 2.55
  }, {
    "id": 59,
    "title": "Stone Reader",
    "author": "Andrej MacLucais",
    "genre": "Documentary",
    "rating": 1.33,
    "year": 2010,
    "publisher": "Ernser Inc",
    "ISBN": "892508443-0",
    "binding": "paperback",
    "pages": 131,
    "language": "Hungarian",
    "price": 68.73
  }, {
    "id": 60,
    "title": "Golem, The (Golem, wie er in die Welt kam, Der)",
    "author": "Jake Barthot",
    "genre": "Fantasy|Horror",
    "rating": 4.07,
    "year": 2011,
    "publisher": "Feil, Hackett and Stroman",
    "ISBN": "584838881-4",
    "binding": "paperback",
    "pages": 916,
    "language": "Bulgarian",
    "price": 55.28
  }, {
    "id": 61,
    "title": "Fubar II (Fubar: Balls to the Wall)",
    "author": "Clerissa Hedin",
    "genre": "Comedy",
    "rating": 3.13,
    "year": 1991,
    "publisher": "Beier, Herman and Vandervort",
    "ISBN": "740195921-6",
    "binding": "hardcover",
    "pages": 1081,
    "language": "Croatian",
    "price": 7.25
  }, {
    "id": 62,
    "title": "Johnny Tremain",
    "author": "Lenka Winkless",
    "genre": "Adventure|Children|War",
    "rating": 3.22,
    "year": 2012,
    "publisher": "Beahan-Dach",
    "ISBN": "613334505-5",
    "binding": "casebound",
    "pages": 613,
    "language": "Malayalam",
    "price": 55.3
  }, {
    "id": 63,
    "title": "White Lightning",
    "author": "Nikoletta Pawden",
    "genre": "Action|Crime|Drama",
    "rating": 2.85,
    "year": 1997,
    "publisher": "Schinner and Sons",
    "ISBN": "926046673-3",
    "binding": "casebound",
    "pages": 1075,
    "language": "Czech",
    "price": 13.16
  }, {
    "id": 64,
    "title": "Starship Troopers",
    "author": "Wash Jeyes",
    "genre": "Action|Sci-Fi",
    "rating": 2.77,
    "year": 1996,
    "publisher": "Okuneva, Schroeder and Hills",
    "ISBN": "133240551-7",
    "binding": "leather-bound",
    "pages": 885,
    "language": "Macedonian",
    "price": 8.53
  }, {
    "id": 65,
    "title": "Nothing Lasts Forever ",
    "author": "Katinka Duffield",
    "genre": "Comedy|Fantasy|Sci-Fi",
    "rating": 4.72,
    "year": 1985,
    "publisher": "Weimann-Yundt",
    "ISBN": "587563854-0",
    "binding": "casebound",
    "pages": 549,
    "language": "Malayalam",
    "price": 83.37
  }, {
    "id": 66,
    "title": "Asterix: The Land of the Gods",
    "author": "Dyana Alison",
    "genre": "Animation",
    "rating": 1.69,
    "year": 1990,
    "publisher": "Carroll and Sons",
    "ISBN": "450960452-1",
    "binding": "leather-bound",
    "pages": 197,
    "language": "Kyrgyz",
    "price": 95.98
  }, {
    "id": 67,
    "title": "Touch of Spice, A (Politiki kouzina)",
    "author": "Blancha Abelov",
    "genre": "Comedy|Drama",
    "rating": 1.94,
    "year": 2000,
    "publisher": "Heathcote, Morar and Langosh",
    "ISBN": "262066090-4",
    "binding": "paperback",
    "pages": 496,
    "language": "Kashmiri",
    "price": 18.37
  }, {
    "id": 68,
    "title": "Girl Cut in Two, The (Fille coupée en deux, La)",
    "author": "Faulkner Smeaton",
    "genre": "Drama|Thriller",
    "rating": 3.87,
    "year": 2002,
    "publisher": "Stokes, Parker and Corkery",
    "ISBN": "454613978-0",
    "binding": "hardcover",
    "pages": 292,
    "language": "Swati",
    "price": 72.9
  }, {
    "id": 69,
    "title": "Confidentially Yours (Vivement dimanche!)",
    "author": "Matt Willavize",
    "genre": "Comedy|Crime|Mystery|Thriller",
    "rating": 4.43,
    "year": 2005,
    "publisher": "Kerluke, Nicolas and Hilpert",
    "ISBN": "530708037-9",
    "binding": "leather-bound",
    "pages": 270,
    "language": "Kannada",
    "price": 30.48
  }, {
    "id": 70,
    "title": "Surviving Progress",
    "author": "Idell Caspell",
    "genre": "Documentary",
    "rating": 3.31,
    "year": 2007,
    "publisher": "Hermann-Davis",
    "ISBN": "731416439-8",
    "binding": "casebound",
    "pages": 266,
    "language": "English",
    "price": 59.08
  }, {
    "id": 71,
    "title": "Frequency",
    "author": "Brandi Mazey",
    "genre": "Drama|Thriller",
    "rating": 4.55,
    "year": 1993,
    "publisher": "Quitzon-Ziemann",
    "ISBN": "369775139-5",
    "binding": "casebound",
    "pages": 295,
    "language": "Swati",
    "price": 42.16
  }, {
    "id": 72,
    "title": "Baboona",
    "author": "Silvester Denes",
    "genre": "Adventure|Documentary",
    "rating": 3.15,
    "year": 1994,
    "publisher": "Wisozk, Baumbach and Hoeger",
    "ISBN": "014817171-0",
    "binding": "leather-bound",
    "pages": 219,
    "language": "Papiamento",
    "price": 17.73
  }, {
    "id": 73,
    "title": "Patrice O'Neal: Elephant in the Room",
    "author": "Brittni Dash",
    "genre": "Comedy",
    "rating": 4.12,
    "year": 2001,
    "publisher": "Ziemann LLC",
    "ISBN": "672587076-7",
    "binding": "casebound",
    "pages": 434,
    "language": "Tswana",
    "price": 83.3
  }, {
    "id": 74,
    "title": "The Butterfly Effect",
    "author": "Farah Hubbold",
    "genre": "Drama|Sci-Fi|Thriller",
    "rating": 3.66,
    "year": 1997,
    "publisher": "Lynch, Smitham and McCullough",
    "ISBN": "371611692-0",
    "binding": "casebound",
    "pages": 607,
    "language": "Punjabi",
    "price": 78.58
  }, {
    "id": 75,
    "title": "Zidane: A 21st Century Portrait (Zidane, un portrait du 21e siècle)",
    "author": "Sher Zoellner",
    "genre": "Documentary",
    "rating": 3.61,
    "year": 1996,
    "publisher": "Howe, Greenfelder and Bartoletti",
    "ISBN": "816180294-7",
    "binding": "paperback",
    "pages": 976,
    "language": "Hungarian",
    "price": 40.91
  }, {
    "id": 76,
    "title": "Santa Fe Trail",
    "author": "April Towne",
    "genre": "Drama|Romance|Western",
    "rating": 4.23,
    "year": 1991,
    "publisher": "Murazik Group",
    "ISBN": "005284206-1",
    "binding": "casebound",
    "pages": 812,
    "language": "Czech",
    "price": 46.47
  }, {
    "id": 77,
    "title": "Faster Pussycat! Kill! Kill!",
    "author": "Halie Kincey",
    "genre": "Action|Crime|Drama",
    "rating": 2.49,
    "year": 1996,
    "publisher": "McDermott-Boyle",
    "ISBN": "590438429-7",
    "binding": "casebound",
    "pages": 713,
    "language": "Hiri Motu",
    "price": 85.0
  }, {
    "id": 78,
    "title": "Villa Rides!",
    "author": "Leonore Collaton",
    "genre": "War|Western",
    "rating": 3.94,
    "year": 2000,
    "publisher": "Goodwin-Mitchell",
    "ISBN": "984185800-2",
    "binding": "casebound",
    "pages": 61,
    "language": "Azeri",
    "price": 82.29
  }, {
    "id": 79,
    "title": "The Adventures of Hercules",
    "author": "Anselm Minette",
    "genre": "Comedy|Fantasy",
    "rating": 2.12,
    "year": 1994,
    "publisher": "Becker Inc",
    "ISBN": "501896920-2",
    "binding": "spiral-bound",
    "pages": 12,
    "language": "Polish",
    "price": 33.66
  }, {
    "id": 80,
    "title": "Good Thief, The",
    "author": "Agneta Heinecke",
    "genre": "Crime|Drama",
    "rating": 4.87,
    "year": 1993,
    "publisher": "Huels Inc",
    "ISBN": "185044394-7",
    "binding": "paperback",
    "pages": 885,
    "language": "Malagasy",
    "price": 10.91
  }, {
    "id": 81,
    "title": "Sandor slash Ida",
    "author": "Maurine Britnell",
    "genre": "Drama|Romance",
    "rating": 4.79,
    "year": 2009,
    "publisher": "Goodwin-Miller",
    "ISBN": "959153882-0",
    "binding": "leather-bound",
    "pages": 167,
    "language": "Thai",
    "price": 80.18
  }, {
    "id": 82,
    "title": "Shadows (Cienie)",
    "author": "Norma Rahlof",
    "genre": "Drama",
    "rating": 2.22,
    "year": 1992,
    "publisher": "Pollich LLC",
    "ISBN": "525581095-9",
    "binding": "leather-bound",
    "pages": 36,
    "language": "Aymara",
    "price": 84.79
  }, {
    "id": 83,
    "title": "Boy Meets Girl",
    "author": "Starla Goodwell",
    "genre": "Comedy|Drama|Romance",
    "rating": 2.62,
    "year": 2001,
    "publisher": "Stroman-Nienow",
    "ISBN": "104904071-6",
    "binding": "casebound",
    "pages": 791,
    "language": "Estonian",
    "price": 41.11
  }, {
    "id": 84,
    "title": "Chatroom",
    "author": "Elmo MacPeice",
    "genre": "Crime|Drama|Mystery|Thriller",
    "rating": 4.13,
    "year": 2000,
    "publisher": "Kris and Sons",
    "ISBN": "527294114-4",
    "binding": "hardcover",
    "pages": 1017,
    "language": "Chinese",
    "price": 39.06
  }, {
    "id": 85,
    "title": "Buckskin Frontier",
    "author": "Melany Casebourne",
    "genre": "Action|Western",
    "rating": 1.6,
    "year": 1985,
    "publisher": "Lowe Inc",
    "ISBN": "967116236-3",
    "binding": "leather-bound",
    "pages": 1024,
    "language": "Montenegrin",
    "price": 45.18
  }, {
    "id": 86,
    "title": "Lineup, The",
    "author": "Elton Robet",
    "genre": "Crime|Drama|Film-Noir",
    "rating": 4.27,
    "year": 2009,
    "publisher": "Denesik, Nikolaus and Quitzon",
    "ISBN": "014275755-1",
    "binding": "casebound",
    "pages": 1067,
    "language": "Telugu",
    "price": 53.13
  }, {
    "id": 87,
    "title": "Hierro ",
    "author": "Devin Purshouse",
    "genre": "Mystery|Thriller",
    "rating": 1.96,
    "year": 2009,
    "publisher": "Dietrich-Greenholt",
    "ISBN": "962252700-0",
    "binding": "casebound",
    "pages": 605,
    "language": "Arabic",
    "price": 20.97
  }, {
    "id": 88,
    "title": "Texasville",
    "author": "Gavrielle Kalf",
    "genre": "Drama",
    "rating": 2.74,
    "year": 2001,
    "publisher": "Beatty-Schowalter",
    "ISBN": "992970484-1",
    "binding": "leather-bound",
    "pages": 567,
    "language": "Khmer",
    "price": 55.55
  }, {
    "id": 89,
    "title": "Teenage Mutant Ninja Turtles III",
    "author": "Kennett Quirke",
    "genre": "Action|Adventure|Children|Comedy|Fantasy",
    "rating": 3.04,
    "year": 2009,
    "publisher": "Harber-Mosciski",
    "ISBN": "765142691-6",
    "binding": "spiral-bound",
    "pages": 928,
    "language": "Ndebele",
    "price": 8.15
  }, {
    "id": 90,
    "title": "Samurai I: Musashi Miyamoto (Miyamoto Musashi)",
    "author": "Amanda Cottisford",
    "genre": "Action|Adventure|Drama",
    "rating": 4.22,
    "year": 1999,
    "publisher": "Volkman and Sons",
    "ISBN": "413829941-6",
    "binding": "leather-bound",
    "pages": 866,
    "language": "Macedonian",
    "price": 73.23
  }, {
    "id": 91,
    "title": "Rosetta",
    "author": "Sigismund Schermick",
    "genre": "Drama",
    "rating": 2.07,
    "year": 1987,
    "publisher": "Gutkowski, Schmidt and Strosin",
    "ISBN": "902998817-7",
    "binding": "leather-bound",
    "pages": 505,
    "language": "Tetum",
    "price": 26.87
  }, {
    "id": 92,
    "title": "Freebie and the Bean",
    "author": "Shari Hidderley",
    "genre": "Action|Comedy",
    "rating": 1.19,
    "year": 2011,
    "publisher": "Halvorson and Sons",
    "ISBN": "604756430-5",
    "binding": "hardcover",
    "pages": 945,
    "language": "Swati",
    "price": 10.45
  }, {
    "id": 93,
    "title": "Tales from the Crypt",
    "author": "Tracey Lemanu",
    "genre": "Horror",
    "rating": 4.47,
    "year": 1984,
    "publisher": "Morissette-Johns",
    "ISBN": "333567249-6",
    "binding": "casebound",
    "pages": 139,
    "language": "Northern Sotho",
    "price": 91.54
  }, {
    "id": 94,
    "title": "Ballad of Narayama, The (Narayama bushiko)",
    "author": "Philip Bullar",
    "genre": "Drama",
    "rating": 3.4,
    "year": 1997,
    "publisher": "Huels, Zieme and Kunze",
    "ISBN": "407996653-9",
    "binding": "leather-bound",
    "pages": 592,
    "language": "Afrikaans",
    "price": 88.76
  }, {
    "id": 95,
    "title": "Popular Music (Populärmusik från Vittula)",
    "author": "Kyle Tearny",
    "genre": "Comedy|Drama",
    "rating": 2.64,
    "year": 1968,
    "publisher": "Schaden, Hansen and Reilly",
    "ISBN": "543291538-3",
    "binding": "spiral-bound",
    "pages": 604,
    "language": "Dutch",
    "price": 43.21
  }, {
    "id": 96,
    "title": "Judy Berlin",
    "author": "Eddie Calendar",
    "genre": "Drama",
    "rating": 4.5,
    "year": 1993,
    "publisher": "Rempel and Sons",
    "ISBN": "641562660-4",
    "binding": "leather-bound",
    "pages": 605,
    "language": "Bislama",
    "price": 67.07
  }, {
    "id": 97,
    "title": "Mo' Better Blues",
    "author": "Sabra Peyro",
    "genre": "Drama|Musical",
    "rating": 2.46,
    "year": 2012,
    "publisher": "Ullrich, Daugherty and Robel",
    "ISBN": "916532124-3",
    "binding": "hardcover",
    "pages": 208,
    "language": "English",
    "price": 45.75
  }, {
    "id": 98,
    "title": "Rancho Notorious",
    "author": "Alfonse Levitt",
    "genre": "Drama|Western",
    "rating": 4.52,
    "year": 2007,
    "publisher": "Goodwin Group",
    "ISBN": "930491203-2",
    "binding": "leather-bound",
    "pages": 924,
    "language": "Swati",
    "price": 20.22
  }, {
    "id": 99,
    "title": "Secret Glory, The",
    "author": "Felice de Pinna",
    "genre": "Documentary",
    "rating": 4.99,
    "year": 2002,
    "publisher": "Oberbrunner-Jacobson",
    "ISBN": "615774780-3",
    "binding": "casebound",
    "pages": 685,
    "language": "Albanian",
    "price": 79.64
  }, {
    "id": 100,
    "title": "Unholy Three, The",
    "author": "Prentice Yearn",
    "genre": "Crime|Drama",
    "rating": 3.11,
    "year": 2011,
    "publisher": "Hilpert-Bogan",
    "ISBN": "170820332-X",
    "binding": "leather-bound",
    "pages": 41,
    "language": "Tamil",
    "price": 49.48
  }];

export default bookArray;